# Use uma imagem base com Python
FROM python:3.12-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo requirements.txt para o diretório de trabalho
COPY requirements.txt /app/

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie o script Python para o diretório de trabalho
COPY seu_script.py /app/

# Comando para executar o script Python
CMD ["python", "seu_script.py"]
